### ISSUE TITLE
Curvessor requires libc 2.29 , but ubuntu 18.04 LTS does not have, Nor support this version.

### ISSUE THREAD

**Issue by RealmportalMC** [unevens/Curvessor#2]
swell: dlopen() failed: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/zack/.vst/Curvessor.so)

**Comment by RealmportalMC** [comment]
i may add the same thing occurs with overdraw

**Comment by unevens** [comment]
Thank you for reporting this issue!
I'm gonna look into it.

**Comment by unevens** [comment]
I'm gonna build the binaries with Ubuntu 18.04 to avoid this issue.

**Comment by unevens** [comment]
I uploaded new binaries built with Ubuntu 18.04.
